# Welcome to the chrony configuration file. See chrony.conf(5) for more
# information about usable directives.

# Include configuration files found in /etc/chrony/conf.d.
confdir /etc/chrony/conf.d

server mmo2.ntp.se iburst minpoll 4 maxpoll 8 polltarget 16 xleave maxdelaydevratio 2 prefer
server time.cloudflare.com iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2
server ntppool3.time.nl iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2 prefer
server ntp1.fau.de iburst minpoll 4 maxpoll 8 polltarget 16 xleave maxdelaydevratio 2 prefer
server ntp3.fau.de iburst minpoll 4 maxpoll 8 polltarget 16 xleave maxdelaydevratio 2 prefer
server time2.uni-stuttgart.de iburst minpoll 4 maxpoll 8 polltarget 16 xleave maxdelaydevratio 2 prefer
server ptbtime1.ptb.de iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2 prefer
server time1.facebook.com iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2 prefer
server time4.facebook.com iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2 prefer
server time2.google.com iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2
server time.dfm.dk iburst minpoll 4 maxpoll 8 polltarget 16 xleave extfield F323 maxdelaydevratio 2 prefer


ratelimit interval 6 burst 15
allow all
minsources 4

log measurements statistics tracking

# Use time sources from DHCP.
sourcedir /run/chrony-dhcp

# Use NTP sources found in /etc/chrony/sources.d.
sourcedir /etc/chrony/sources.d

# This directive specify the location of the file containing ID/key pairs for
# NTP authentication.
keyfile /etc/chrony/chrony.keys

# This directive specify the file into which chronyd will store the rate
# information.
driftfile /var/lib/chrony/chrony.drift

# Save NTS keys and cookies.
ntsdumpdir /var/lib/chrony

# Uncomment the following line to turn logging on.
#log tracking measurements statistics

# Log files location.
logdir /var/log/chrony

# Stop bad estimates upsetting machine clock.
maxupdateskew 100.0

# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can't be used along with the 'rtcfile' directive.
rtcsync

# Step the system clock instead of slewing it if the adjustment is larger than
# one second, but only in the first three clock updates.
makestep 1 3

# Get TAI-UTC offset and leap seconds from the system tz database.
# This directive must be commented out when using time sources serving
# leap-smeared time.
leapsectz right/UTC

# Allow exporter/chronyc to reach the command socket (UDP 323)
bindcmdaddress 0.0.0.0
bindcmdaddress ::
